version: 2

project_name: gosymdb

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: gosymdb
    ldflags:
      - -s -w
      - -X github.com/walkindude/gosymdb/internal/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - "^docs:"
      - "^test:"
